script: ./gradlew check -PbintrayUser=x -PbintrayKey=y
language: java

jdk:
  - oraclejdk8

# Skip ./gradlew assemble
install: /bin/true

notifications:
  email: false

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls
